package guru.springframework.spring5webapp.domain;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

//we will annotate the class to turn out POJO into an actual JPA entity
@Entity //this tells Hibernate that this is an entity
public class Author {
    //POJO

    //need to add a primary key else it will complain once we add the Entity annotation
    @Id //Id from Persistence package
    @GeneratedValue(strategy = GenerationType.AUTO) //this value will be auto generated by the underlying database
    private Long id;

    private String firstName;
    private String lastName;

    //set this up as a many to many relationship
    @ManyToMany(mappedBy = "authors")
    private Set<Book> books = new HashSet<>();

    //You can use IntelliJ Generate context menu (cmd + N) to auto generate constructors and getters / setters

    //JPA requires a zero args constructor
    public Author() {
    }

    //another constructor with all args
    public Author(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Set<Book> getBooks() {
        return books;
    }

    public void setBooks(Set<Book> books) {
        this.books = books;
    }

    //implement a toString method so that intelliJ can display useful info on these objects
    @Override
    public String toString() {
        return "Author{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                '}';
    }

    //implement equals and hashCode to handle the JPA leakage based on the id field
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Author author = (Author) o;
        return Objects.equals(id, author.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }


}
